# Simulation 1
# Configuration File

title = "Simulation 1 - 15D"

dims = 15
omega = 1.0
dt = 0.01
cycles = 4
T_initial = 1.0

[phaseonium]
phi_hot = 3.0
T_hot = 1.2
phi_cold = 4.0
T_cold = 0.7

[cavity]
mass = 1.0
surface = 1.0
length = 1.0
alpha = 3.1415926535
acceleration = 0.0
external_force = 0.5

[stroke_time]
isochore = 25000
adiabatic = 1000

[samplings]
isochore = 20
adiabatic = 10

[loading]
load_state = true
filename = "state_cascade_nonthermal_12cycles"
past_cycles = 12
