# Simulation 1
# Configuration File

title = "Initial State Coherent - 2photons - 20D"

dims = 20
omega = 2.0
dt = 0.01
cycles = 15
alpha_initial = 1.4142135623730951

[phaseonium]
phi_hot = 3.0
T_hot = 1.5
phi_cold = 4.0
T_cold = 1.0

[cavity]
mass = 1.0
surface = 1.0
length = 1.0
alpha = 3.1415926535
acceleration = 0.0
external_force = 0.5

[stroke_time]
isochore = 100000
adiabatic = 1000

[samplings]
isochore = 20
adiabatic = 10

[loading]
load_state = true
filename = "state_cascade_nonthermal_12cycles"
past_cycles = 12
