# Configuration File

description = """
Simulation 2 - 15D \
- Long thermalization - No entanglement
"""

dims = 15
omega = 5.0
dt = 0.01
cycles = 1
T_initial = 2.0

[phaseonium]
phi_hot = 1.8
T_hot = 3.0
phi_cold = 2.4
T_cold = 1.5

[cavity]
mass = 1.0
surface = 1.0
min_length = 1.0
max_length = 1.1
alpha = 3.1415926535
acceleration = 0.0
external_force = 2.5

[stroke_time]
isochore = 14000
adiabatic = 2000

[samplings]
isochore = 150
adiabatic = 50

[loading]
load_state = true
filename = "state"
past_cycles = 4
